[package]
name = "rpc-api"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
prost = "0.14.4"
scylla = "1.8.0"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal", "sync"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"

[dev-dependencies]
tokio-stream = { version = "0.1", features = ["net"] }

[build-dependencies]
tonic-prost-build = "0.14.6"
