[package]
name = "grpc-scylladb-starter"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
async-trait = "0.1"
prost = "0.14.4"
prost-types = "0.14.4"
scylla = "1.8.0"
thiserror = "2"
x509-parser = "0.16"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal", "sync"] }
tonic = { version = "0.14.6", features = ["tls-ring", "tls-connect-info"] }
tonic-prost = "0.14.6"

[dev-dependencies]
tokio-stream = { version = "0.1", features = ["net"] }


[build-dependencies]
protoc-bin-vendored = "3"
tonic-prost-build = "0.14.6"
