syntax = "proto3";

package channel;

import "google/protobuf/empty.proto";

service ChannelService {
  rpc CreateChannel(CreateChannelRequest) returns (Channel);
  rpc GetChannel(GetChannelRequest) returns (Channel);
  rpc UpdateChannel(UpdateChannelRequest) returns (Channel);
  rpc DeleteChannel(DeleteChannelRequest) returns (google.protobuf.Empty);
  rpc ListChannels(ListChannelsRequest) returns (ListChannelsResponse);
}

message Channel {
  string id = 1;
  string name = 2;
  uint64 created_at_unix_ms = 3;
}

message CreateChannelRequest {
  string name = 1;
}

message GetChannelRequest {
  string id = 1;
}

message UpdateChannelRequest {
  string id = 1;
  string name = 2;
}

message DeleteChannelRequest {
  string id = 1;
}

message ListChannelsRequest {
  bytes page_token = 1;
  uint32 limit = 2;
}

message ListChannelsResponse {
  repeated Channel channels = 1;
  bytes next_page_token = 2;
}
